## FUNCTION Vs MODULES Vs METHOD Vs LIBRAIES Vs PACKAGES

### "Pandas is a Python library for data analysis. pandas itself distributed as a Python package and contains modules, classes, and functions that provide data-manipulation functionality."

# PANDAS LIBRARY\PACKAGE
- used for dataframe and operation
- Data analysis / manipulation library
### Using areas
- tables
- excel,csv etc
- dataframes
- rows and columns
- filtering
- sorting
- grouping
- handling data missing values
- data cleaning
### Examples;
- import pandas as pd
- df=pd.read_csv(filepath_or_buffer="student.csv")
- print(df.head())
- print(df["marks"].mean())

In [1]:
import pandas as pd
super_store=pd.read_csv(filepath_or_buffer="samplesuperstore.csv")

In [2]:
super_store

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

## relative path vs copy path
1. Copy Path is ideal when you need to share the exact location of a file or use it in scripts that require a fixed reference.
- c:/
2. Copy Relative Path is better suited for projects or scripts where portability is important, as it adapts to the current working directory.
  - sample.csv
3. if the file is not found in current directory means just put the r"
- filepath_or_buffer=r"c:\.....\"
- r means read the current directory

# NUMPY Library \ package
- used for numerical operation using the python
- Numpy-Numerical Python
### Works along with
- arrays operations
- mathematical operations
- linear algebra
- fasy computations on maths
- nummerical operations
### Examples;
- import numpy as np
- marks=np.arr([12,34,12])
- print(marks.mean())

## SHORTCUT NOTES
- shift + tab on function to see what it will do

In [4]:
import numpy as np
np.repeat(a=super_store,repeats=2,axis=0)

array([[1, 'US-2023-103800', '1/3/2023', ..., 2, 0.2, 5.5512],
       [1, 'US-2023-103800', '1/3/2023', ..., 2, 0.2, 5.5512],
       [2, 'US-2023-112326', '1/4/2023', ..., 2, 0.8, -5.487],
       ...,
       [10193, 'US-2026-143259', '12/30/2026', ..., 7, 0.0, 2.7279],
       [10194, 'CA-2026-143500', '12/30/2026', ..., 3, 0.2, -0.6048],
       [10194, 'CA-2026-143500', '12/30/2026', ..., 3, 0.2, -0.6048]],
      shape=(20388, 21), dtype=object)

- repest id s function
- a= is a parameter
- super_store is a argument (value pass to the parameter)
- repeat is a repeatin the row or column on times
- axis = 0 is a row
- axis = 1 is a colunm
- axis default value is o

In [6]:
pd.DataFrame(data=np.repeat(a=super_store,repeats=2,axis=0))

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
2,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,0.8,-5.487
3,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,0.8,-5.487
4,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20383,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
20384,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.93,7,0.0,2.7279
20385,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.93,7,0.0,2.7279
20386,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048
20387,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [7]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.10.9)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [8]:
from matplotlib import pyplot as plt

In [4]:
import matplotlib.pyplot as plt

In [8]:
plt.hist(super_store["Ship Date"])

NameError: name 'super_store' is not defined

In [9]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2->seaborn) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
pip install plotly

Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from plotly) (26.2)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 453.5 kB/s eta 0:00:21
   -- ------------------------------------- 0.5/9.9 MB 453.5 kB/s eta 0:00:21
   -- ------------------------------------- 0.5/9.9 MB 453.5 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.9 MB 447.3 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.9 MB 447.3 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.9 MB 447.3 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.9 MB 457.8 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.9 MB 457.8 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 466.0 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.9 MB 466.0 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.9 MB 466.0 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.9 MB 458.5 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.9 MB 458.5 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.9 MB 458.5 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.9 MB 443.4 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.9 MB 443.4 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.9 MB 443.4 kB/s eta 0:00:19
   -------- ------------------------------- 2.1/9.9 MB 441.5 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.9 MB 441.5 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.9 MB 441.5 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.9 MB 441.5 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.9 MB 427.5 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.9 MB 427.5 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.9 MB 427.5 kB/s eta 0:00:18
   ---------- ----------------------------- 2.6/9.9 MB 417.1 kB/s eta 0:00:18
   ---------- ----------------------------- 2.6/9.9 MB 417.1 kB/s eta 0:00:18
   ---------- ----------------------------- 2.6/9.9 MB 417.1 kB/s eta 0:00:18
   ----------- ---------------------------- 2.9/9.9 MB 421.6 kB/s eta 0:00:17
   ----------- ---------------------------- 2.9/9.9 MB 421.6 kB/s eta 0:00:17
   ------------ --------------------------- 3.1/9.9 MB 425.2 kB/s eta 0:00:16
   ------------ --------------------------- 3.1/9.9 MB 425.2 kB/s eta 0:00:16
   ------------ --------------------------- 3.1/9.9 MB 425.2 kB/s eta 0:00:16
   ------------- -------------------------- 3.4/9.9 MB 428.4 kB/s eta 0:00:16
   ------------- -------------------------- 3.4/9.9 MB 428.4 kB/s eta 0:00:16
   ------------- -------------------------- 3.4/9.9 MB 428.4 kB/s eta 0:00:16
   -------------- ------------------------- 3.7/9.9 MB 427.7 kB/s eta 0:00:15
   -------------- ------------------------- 3.7/9.9 MB 427.7 kB/s eta 0:00:15
   -------------- ------------------------- 3.7/9.9 MB 427.7 kB/s eta 0:00:15
   -------------- ------------------------- 3.7/9.9 MB 427.7 kB/s eta 0:00:15
   --------------- ------------------------ 3.9/9.9 MB 421.0 kB/s eta 0:00:15
   --------------- ------------------------ 3.9/9.9 MB 421.0 kB/s eta 0:00:15
   --------------- ------------------------ 3.9/9.9 MB 421.0 kB/s eta 0:00:15
   --------------- ------------------------ 3.9/9.9 MB 421.0 kB/s eta 0:00:15
   ---------------- ----------------------- 4.2/9.9 MB 411.9 kB/s eta 0:00:14
   ---------------- ----------------------- 4.2/9.9 MB 411.9 kB/s eta 0:00:14
   ---------------- ----------------------- 4.2/9.9 MB 411.9 kB/s eta 0:00:14
   ----------------- ---------------------- 4.5/9.9 MB 406.7 kB/s eta 0:00:14
   ----------------- ---------------------- 4.5/9.9 MB 406.7 kB/s eta 0:00:14
   ----------------- ---------------------- 4.5/9.9 MB 406.7 kB/s eta 0:00:14
   ----------------- ---------------------- 4.5/9.9 MB 406.7 kB/s eta 0:00:14
   ------------------- -------------------- 4.7/9.9 MB 399.5 kB/s eta 0:00:13
   ------------------- -------------------- 4.7/9.9 MB 399.5 kB/s eta 0:00:13
   ------------------- -------------------- 4.7/9.9 MB 399.5 kB/s eta 0:00:13
   ------------------- -------------------- 4.7/9.9 MB 399.5 kB/s eta 0:00:13
   -------------------- ------------------- 5.0/9.9 MB 394.8 kB/s eta 0:00:13
   -------------------- ------------------- 5.0/9.9 MB 394.8 kB/s eta 0:00:13
   -------------------- ------------------- 5.0/9.9 MB 394.8 kB/s eta 0:00:13
   --------------------- ------------------ 5.2/9.9 MB 394.5 kB/s eta 0:00:12
   --------------------- ------------------ 5.2/9.9 MB 394.5 kB/s eta 0:00:12
   --------------------- ------------------ 5.2/9.9 MB 394.5 kB/s eta 0:00:12
   ---------------------- ----------------- 5.5/9.9 MB 394.8 kB/s eta 0:00:12
   ---------------------- ----------------- 5.5/9.9 MB 394.8 kB/s eta 0:00:12
   ---------------------- ----------------- 5.5/9.9 MB 394.8 kB/s eta 0:00:12
   ---------------------- ----------------- 5.5/9.9 MB 394.8 kB/s eta 0:00:12
   ----------------------- ---------------- 5.8/9.9 MB 394.1 kB/s eta 0:00:11
   ----------------------- ---------------- 5.8/9.9 MB 394.1 kB/s eta 0:00:11
   ----------------------- ---------------- 5.8/9.9 MB 394.1 kB/s eta 0:00:11
   ------------------------ --------------- 6.0/9.9 MB 391.0 kB/s eta 0:00:10
   ------------------------ --------------- 6.0/9.9 MB 391.0 kB/s eta 0:00:10
   ------------------------ --------------- 6.0/9.9 MB 391.0 kB/s eta 0:00:10
   ------------------------- -------------- 6.3/9.9 MB 395.8 kB/s eta 0:00:10
   ------------------------- -------------- 6.3/9.9 MB 395.8 kB/s eta 0:00:10
   -------------------------- ------------- 6.6/9.9 MB 398.3 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.9 MB 398.3 kB/s eta 0:00:09
   --------------------------- ------------ 6.8/9.9 MB 405.6 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.9 MB 405.6 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.9 MB 405.6 kB/s eta 0:00:08
   ---------------------------- ----------- 7.1/9.9 MB 408.1 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.9 MB 414.4 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.9 MB 414.4 kB/s eta 0:00:07
   ------------------------------ --------- 7.6/9.9 MB 419.8 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.9 MB 419.8 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.9 MB 425.7 kB/s eta 0:00:05
   ------------------------------- -------- 7.9/9.9 MB 425.7 kB/s eta 0:00:05
   -------------------------------- ------- 8.1/9.9 MB 430.6 kB/s eta 0:00:05
   --------------------------------- ------ 8.4/9.9 MB 437.4 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 437.4 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/9.9 MB 443.7 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 443.7 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 443.7 kB/s eta 0:00:03
   ----------------------------------- ---- 8.9/9.9 MB 444.0 kB/s eta 0:00:03
   ----------------------------------- ---- 8.9/9.9 MB 444.0 kB/s eta 0:00:03
   ----------------------------------- ---- 8.9/9.9 MB 444.0 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 443.2 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 443.2 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 443.2 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 443.2 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 443.2 kB/s eta 0:00:02
   ---------------------------------------  9.7/9.9 MB 445.7 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 449.1 kB/s  0:00:22
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# PLOTY LIBRARY/PACKAGE

### Plotly in Python is a data visualization library used to create interactive, high-quality, and web-based charts.

## Key Uses of Plotly in Python

### Interactive Visualizations

1. Unlike static plots (e.g., Matplotlib), Plotly charts allow zooming, panning, hovering for tooltips, and dynamic updates.
Wide Range of Chart Types
2. Supports line charts, bar charts, scatter plots, pie charts, histograms, heatmaps, 3D plots, maps, and more.
Web & Dashboard Integration
3. Works seamlessly with Dash (a Python framework) to build interactive dashboards without needing JavaScript.
Publication-Quality Graphics
4. Produces visually appealing, professional-grade plots suitable for reports and presentations.
Multiple Output Formats

5. Can display in Jupyter Notebooks, save as HTML, or embed in web applications.

---------------------------------------------------------------------------------------------------------------
# MATPLOTLIB LIB/PACKAGE

- Matplotlib is a popular data visualization library in Python used to create a wide variety of static, interactive, and animated plots.

### Main Uses of Matplotlib
1. Data Visualization
  - Helps represent data in a graphical format (line charts, bar charts, scatter plots, histograms, pie charts, etc.).
Makes it easier to understand trends, patterns, and relationships in data.
2. Customizable Plots
  - You can control every aspect of a plot: colors, labels, titles, legends, grid lines, and styles.
3. Supports Multiple Output Formats
  - Can save plots as PNG, JPG, SVG, PDF, etc.
4. Works in Jupyter Notebooks, Python scripts, and interactive environments.
5. Integration with Other Libraries
- Works well with NumPy, Pandas, and SciPy for scientific computing.
Often used alongside Seaborn for more advanced statistical visualizations.

-----------------------------------------------------------------------------
WE WILL SEE SEABORN DIFFERENCE LATER

# END!!